apiVersion: v1
kind: Service
metadata:
  name: investments-service
spec:
  selector:
    app: investments-service
  ports:
  - port: 8003
    targetPort: 8003
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: investments-db
spec:
  selector:
    app: investments-db
  ports:
  - port: 5432
    targetPort: 5432